apiVersion: v1
kind: ConfigMap
metadata:
  name: project-configmap
  namespace: project
data:
  BACKEND_URL: http://localhost:8081/api
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: postgres-stset-0.postgres-svc
