apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server-dep
spec:
  selector:
    matchLabels:
      app: express-server
  template:
    metadata:
      labels:
        app: express-server
    spec:
      containers:
        - name: express-server
          image: nickleezx/the_project:0.0.2
          env:
            - name: PORT
              value: "3002"

