apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-dep
  namespace: project
spec:
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      # volumes: 
      #   - name: image-pv
      #     persistentVolumeClaim:
      #       claimName: the-project-claim
      containers:
        - name: express-server
          image: nickleezx/the_project:0.0.6
          env:
            - name: PORT
              value: "3002"
            - name: FRONTEND_URL
              value: "http://localhost:8081"
        - name: frontend
          image: nickleezx/the_project_fe:0.0.6
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: project-configmap
                  key: BACKEND_URL


