apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: the-project-claim
  namespace: project
spec:
  storageClassName: pv-filesystem
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
