apiVersion: v1
kind: Service
metadata:
  name: the-project-svc
spec:
  type: ClusterIP
  selector: 
    app: the-project
  ports:
    - name: server-port
      protocol: TCP
      port: 1234
      targetPort: 3002
    - name: frontend-port
      protocol: TCP
      port: 2345
      targetPort: 4173
  