apiVersion: v1
kind: Service
metadata:
  name: express-server-svc
spec:
  type: NodePort
  selector: 
    app: express-server
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3002
  