apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: log-output-file
          emptyDir: {}
        # - name: ping-pong-pv
        #   persistentVolumeClaim:
        #     claimName: ping-pong-claim
      containers:
        - name: hashgenerator
          image: nickleezx/log_output:0.0.8
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
            - name: BASE_URL
              value: http://ping-pong-svc:1234/api
          volumeMounts:
            - name: log-output-file
              mountPath: /usr/src/app/shared
            # - name: ping-pong-pv
            #   mountPath: /usr/src/app/shared1
        - name: file-reader-app
          image: nickleezx/file-reader-app:0.0.8
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: log-output-file
              mountPath: /usr/src/app/shared

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      # volumes:
      #   - name: ping-pong-pv
      #     persistentVolumeClaim:
      #       claimName: ping-pong-claim
      containers:
        - name: ping-pong-app
          image: nickleezx/ping-pong-app:0.0.4
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
          # volumeMounts:
          #   - name: ping-pong-pv
          #     mountPath: /usr/src/app/shared1