apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      volumes:
        - name: log-output-file
          emptyDir: {}
      containers:
        - name: hashgenerator
          image: nickleezx/log_output:0.0.5
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3002"
          volumeMounts:
            - name: log-output-file
              mountPath: /usr/src/app/shared
        - name: file-reader-app
          image: nickleezx/file-reader-app:0.0.8
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: log-output-file
              mountPath: /usr/src/app/shared

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
        - name: ping-pong-app
          image: nickleezx/ping-pong-app:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3001"