apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ping-pong-claim
  namespace: exercises
spec:
  storageClassName: pv-filesystem
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
