apiVersion: v1
kind: Service
metadata:
  name: hashgenerator-svc
spec:
  type: ClusterIP
  selector:
    app:
      hashgenerator
  ports:  
    - port: 1234
      protocol: TCP
      targetPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: ping-pong-app
  ports:
    - port: 1234
      protocol: TCP
      targetPort: 3001